server:
  port: 3031

allowed:
  origins: http://localhost:3000

external:
  access-key: #{your api source access key}
  base-url: https://api.exchangeratesapi.io/v1

#                            #
# JDBC connection properties #
#                            #
spring:
  application:
    name: exchange_rate_app_springboot
  datasource:
    url: #{Your Database Url}
    username:  #{your username}
    password:  #{your password }
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          jwk-set-uri: https://www.googleapis.com/service_accounts/v1/jwk/securetoken%40system.gserviceaccount.com

  jpa:
    hibernate:
      ddl-auto: update # options: none, validate, update, create, create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  data:
    rest:
      base-path: /api
      detection-strategy: ANNOTATED

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: # {Input yours}
            client-secret: # { Input yours }
            scope: profile, email
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo

logging:
  level:
    root: "info"
    com.example.demo: DEBUG

#  Testing ignore