spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
allowed:
  origins: http://localhost:3000
external:
  access-key: bb7e43d9fe8d02373228c2c8f5490b28
  base-url: https://api.exchangeratesapi.io/v1

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate: DEBUG
