server:
  port: 5000

allowed:
  origins: http://localhost:3000

external:
  access-key: bb7e43d9fe8d02373228c2c8f5490b28
  base-url: https://api.exchangeratesapi.io/v1

#                            #
# JDBC connection properties #
#                            #
spring:
  application:
    name: exchange_rate_app_springboot
  datasource:
    url: jdbc:mysql://mydbinstance.cdy44kysw0we.eu-north-1.rds.amazonaws.com:3306/exchange-rate-schema
    username: admin
    password: gjeniketenike

  #  security:
  #    oauth2:
  #      resourceserver:
  #        jwt:
  #          jwk-set-uri: https://www.googleapis.com/service_accounts/v1/jwk/securetoken%40system.gserviceaccount.com

  jpa:
    hibernate:
      ddl-auto: update # options: none, validate, update, create, create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  data:
    rest:
      base-path: /api
      detection-strategy: ANNOTATED

logging:
  level:
    root: "info"
    com.example.demo: DEBUG

#  Testing ignore